config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'dresses#home'
  get '/home', to: 'dresses#home'
  resources :users, only: %i[show] do
    resources :dresses, only: %i[index create edit update]
  end

  resources :dresses, except: %i[ destroy] do
    resources :rentals, only: %i[create]
  end
  resources :rentals, only: %i[show]
  resources :dresses, only: %i[filter]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dress.rb
class Dress < ApplicationRecord
  CATEGORIES =  %w[evening cocktail day special]
  SIZES = %w[XS S M L XL]

  belongs_to :user
  has_many :rentals
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :size, presence: true
  validates :heigth, presence: true
  mount_uploader :photo, PhotoUploader

  scope :by_title_and_description, -> (title_or_desc){where("title @@ :title_or_desc OR description @@ :title_or_desc", title_or_desc: title_or_desc)}
  scope :by_size, -> (size){where("size ILIKE :size", size: size)}
  scope :by_category, -> (category){where("category ILIKE :category", category: category)}

  def self.search(search, size, category)

    result = Dress.all

    if search.present?
      result = result.by_title_and_description(search)
    end
    
    if size.present?
      result = result.by_size(size)
    end

    if category.present?
      result = result.by_category(category)
    end

    return result
  end
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :dress
  validates :price, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  DEFAULT_PHOTO_URL = ''
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :dresses, dependent: :destroy
  has_many :rentals
  mount_uploader :photo, PhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true

  def photo_or_default
    if photo.file.nil?
      DEFAULT_PHOTO_URL
    else
      photo
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/dresses_controller.rb
class DressesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :show, :index]
  before_action :set_dress, only: [:show]

  def home
    @dresses = Dress.search(params[:search], params[:size], params[:category])
  end

  def index
    search = params[:search]
    size = params[:size]
    category = params[:category]
    @dresses = Dress.search(params[:search], params[:size], params[:category])
  end

  def show
    @rental = Rental.new
  end

  def new
    @dress = Dress.new
  end

  def edit
    @dress = Dress.find(params[:id])
  end

  def create
    @dress = Dress.new(dress_params)
    @dress.user = current_user
    if @dress.save
      redirect_to dress_path(@dress), notice: 'Your dress was successfully listed!'
    else
      render :new
    end
  end

  def destroy
    @dress.destroy
    redirect_to dress_path
  end

  private

  def dress_params
    params.require(:dress).permit(:title, :description, :category, :price, :size, :heigth, :search, :photo)
  end

  def set_dress
    @dress = Dress.find(params[:id])
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :photo, :first_name, :last_name)
  end

  def account_update_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :photo, :first_name, :last_name)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show]

  def show; end

  def create
    @dress = Dress.find(params[:dress_id])
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.dress = @dress
    @rental.price = @dress.price
    if @rental.save
      redirect_to @rental
    else
      render 'dresses/show'
    end
  end

  private

  def set_rental
    @rental = Rental.find(params[:id])
  end

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @dresses = @user.dresses
    @dress = Dress.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dresses/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    © 2018 One Day One Dress. All Rights Reserved. <i class="fa fa-heart"></i>
  </div>
</div>

app/views/dresses/_form.html.erb
<div class="container">
  <%= simple_form_for(@dress) do |f| %>
     <%= f.error_notification %>
     <div class="input-box">
       <%= f.input :title, class: '', input_html: { class: '' } %>
     </div>
       <div class="input-box">
       <%= f.input :description %>
     </div>
     <div class="input-box">
       <%= f.input :heigth %>
     </div>
     <div class="input-box">
       <%= f.input :category, collection: Dress::CATEGORIES %>
     </div>
     <div class="input-box">
       <%= f.input :size, collection: Dress::SIZES %>
     </div>
     <div class="input-box">
       <%= f.input :price %>
     </div>
      <div class="input-box">
       <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
     </div>
     <div class="button submit">
       <%= f.button :submit %>
     </div>
   <% end %>
</div>

app/views/dresses/edit.html.erb
<div class="container">
  <div class="row">
  <div class="col-md-12">

        <h3>Edit your dress:</h3>
        <%= simple_form_for [@user, @dress] do |f| %>
          <%= f.input :title %>
          <%= f.input :size %>
          <%= f.input :category %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :photo %>
            <%= f.input :photo_cache, as: :hidden %>
          <%= f.button :submit, class: "btn btn-success" %>
          <%= link_to("Cancel", user_path, class: "btn btn-warning") %>
        <% end %>
    </div>
  </div>
</div>

app/views/dresses/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>OneDayOneDress </title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="main.css">
  <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
</head>
<body>

<div class="jumbotron banner">
  <div class="container">
    <h2>Welcome to the modern dress closet!</h2>
    <p>Buy less. Wear more. Be you.</p>
    <p><%= link_to 'Rent a Dress', dresses_path, class: "btn btn-default btn-lg" %></p>
  </div>
</div>

</body>
</html>

app/views/dresses/index.html.erb
<div class="dresses-grid">
  <% @dresses.each do |dress| %>
    <div class="dresses-grid-card" >
      <div class="thumbnail">
        <div class="dress-img" style='background-image: url(<%= cl_image_path dress.photo %>)'></div>
        <div class="caption">
          <h3><%= link_to dress.title.capitalize, dress_path(dress) %></h3>
          <p><%= dress.description %></p>
          <p>Size: <strong><%= dress.size %></strong></p>
          <p>Category: <strong><%= dress.category %></strong></p>
          <p>Price: MXN <strong>$<%= dress.price %></strong></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/dresses/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="new-title">List a new Dress</h1>
    <div class="new-form"><%= render 'form' %>
    </div>
  </div>
</div>

app/views/dresses/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <h1><%= @dress.title.upcase %></h1>
      <h2>Category: <%= @dress.category %></h2>
      <p>Size: <%= @dress.size %></p>
      <p><%= @dress.description %></p>
      <p>Length <%= @dress.heigth %>cm .</p>
      <p>Price per day: <%= @dress.price %>$ MXN</p>
      <div>
        <h3>What dates do you need it?</h3>
        <%= simple_form_for([@dress, @rental]) do |f| %>
        <%= f.input :start_date, wrapper_html: { class: 'flex-select' }, as: :date, html5: true %>
        <%= f.input :end_date, wrapper_html: { class: 'flex-select' }, as: :date, html5: true %>
        <%= f.submit %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-6">
      <%= cl_image_tag @dress.photo, height: 800 %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300,500|Julius+Sans+One" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <title>RailsOneDayOneDress</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
   <navbar> <%= render 'shared/navbar' %> </navbar>
    <%= render 'shared/flashes' %>
    <div class="content">
      <%= yield %>
    </div>
    <footer><%= render 'dresses/footer' %></footer>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/rentals/_form.html.erb
<%= simple_form_for [dress, rental] do |f| %>
  <%= f.input :start_date  %>
  <%= f.input :end_date %>
  <%= f.submit %>
<% end %>

app/views/rentals/show.html.erb
<div class="container text-center" style='padding: 15vh'>
 <div class="row">
   <div class="col-sm-12 col-md-6 col-md-offset-3">
     <div class="rental">
      <h1 class="rental_title"> YOU GOT IT!</h1>

      <p> You chose the <%= @rental.dress.title.capitalize %></p>
      <p> It is yours from <%= @rental.start_date.strftime('%A, %b %d') %> to <%= @rental.end_date.strftime('%A, %b %d') %>. <br> It will be available for pick up anytime between those days.</p>

      <p>The total for the dress wil be: <%= @rental.price * (@rental.end_date - @rental.start_date).to_i  %>$</p>

      <%# <%= link_to 'Pay', user_path(current_user), class: "btn btn-primary"  %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "List a dress", new_dress_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= render 'shared/search' %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.photo_or_default, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= render 'shared/search' %>

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_up", default: "Sign up"), new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_search.html.erb
<div class="advanced_search_container">
    <div class="input-group" id="adv-search">
      <%= form_tag(dresses_path, {class: 'search form-inline my-2 my-lg-0', method: 'get'}) do %>
        <%= text_field_tag :search, '', class: " mr-sm-2", placeholder: "Find The Dress" %>
        <%= select_tag :size, options_for_select(Dress::SIZES), :prompt => "size", class: "select", style: "border-bottom:0px solid !important; margin-left:5px;width: 70px;"%>
        <%= select_tag :category, options_for_select(Dress::CATEGORIES), :prompt => "category" , class: "select", style: "border-bottom:0px solid !important; margin-left:5px;width: 70px;" %>
        <%= submit_tag 'Search', class: " search btn btn-outline-success my-2 my-sm-0 "%>
      <% end %>
    </div>
</div>

app/views/users/_form.html.erb
 <div class="form">
  <%= simple_form_for(@dress) do |f| %>
     <%= f.error_notification %>
     <div class="input-box">
       <%= f.input :title %>
     </div>
       <div class="input-box">
       <%= f.input :description %>
     </div>
     <div class="input-box">
       <%= f.input :heigth %>
     </div>
     <div class="input-box">
       <%= f.input :category, collection: Dress::CATEGORIES %>
     </div>
     <div class="input-box">
       <%= f.input :size, collection: Dress::SIZES %>
     </div>
      <div class="input-box">
       <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
     </div>
     <div class="button submit">
       <%= f.button :submit %>
     </div>
   <% end %>
   <% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Welcome <%= @user.first_name.capitalize %>!</h2>
      <h3><%= @user.email %></h3>
      <h4>My Dress Rentals:</h4>
      <ul>
        <% if @user.rentals.any? %>
          <% @user.rentals.each do |rental| %>
          <li><%= link_to rental.dress.title, rental_path(rental) %></li>
          <% end %>
        <% else %>
          <p>You don't have any rented dresses yet. You should rent one! </p>
        <% end %>
      </ul>
      <% if @user.dresses.any? %>
        <h4>My Dresses:</h4>
        <ul>
          <% @user.dresses[0..(@dresses.size - 1)].each do |dress| %>
            <li>
              <p><strong>Title:</strong><%= link_to dress.title, dress_path(dress) %> <strong>| Description:</strong> <%= dress.description %> <strong>Size:</strong><%= dress.size%> </p>
              <p><%= link_to("Edit", edit_user_dress_path(@user, dress)) %></p>
              <h5>Dress current rentals:</h5>
              <% dress.rentals.each do |rental| %>
              <p><%= link_to rental.start_date, rental_path(rental) %></p>
              <% end %>
              </li>
          <% end %>
        </ul>
      <% else  %>
        <p>You have not created any dresses for rent. You should create one!</p>
      <% end  %>
    </div>
  </div>
</div>